#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tk-ProgressBar-Mac
version:      1.2
version_from: Mac.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
